const test = require("node:test");
const assert = require("node:assert/strict");
const m = require("../../pb_hooks/lib/match.js");

function q(title) { return m.parseTitle(title).qualifiers.join(","); }
function base(title) { return m.parseTitle(title).base; }

test("qualifiers are preserved and compared, noise is stripped", () => {
  assert.equal(q("Song (Live)"), "live");
  assert.equal(q("Song - Live at Wembley 1986"), "live");
  assert.equal(q("Song - 2011 Remaster"), "remaster");
  assert.equal(q("Song (Remastered 2009)"), "remaster");
  assert.equal(q("Song (Acoustic)"), "acoustic");
  assert.equal(q("Song (Sped Up)"), "sped_up");
  assert.equal(q("Song (Slowed + Reverb)"), "reverb,slowed");
  assert.equal(q("Song (Radio Edit)"), "edit");
  assert.equal(q("Song (Extended Mix)"), "extended");
  assert.equal(q("Song (Original Mix)"), "");
  assert.equal(q("Song (Skrillex Remix)"), "remix");
  assert.equal(q("Song (Cover)"), "cover");
  assert.equal(q("Song (Taylor's Version)"), "rerecorded");
  assert.equal(q("Song (Spanish Version)"), "v:spanish version");
  assert.equal(q("Song (Official Music Video)"), "");
  assert.equal(q("Song [Lyrics]"), "");
  assert.equal(q("Song (Explicit)"), "");
  assert.equal(base("Song (Official Video) [HD]"), "song");
  assert.equal(base("Song | Official Audio"), "song");
});

test("titles keep meaningful brackets and drop featured credits", () => {
  assert.equal(base("(I Can't Get No) Satisfaction"), "i cant get no satisfaction");
  assert.equal(base("Song (feat. Someone)"), "song");
  assert.equal(base("Song feat. Someone Else"), "song");
  assert.equal(base("Rock & Roll"), "rock and roll");
  assert.equal(base("Déjà Vu"), "deja vu");
  assert.notEqual(base("紅蓮華"), "");
  assert.equal(base("紅蓮華"), base("紅蓮華 (Official Video)"));
});

test("artist agreement handles joint credits and 'the'", () => {
  assert.equal(m.artistsAgree(["Simon & Garfunkel"], ["Simon & Garfunkel"]), true);
  assert.equal(m.artistsAgree(["Calvin Harris"], ["Calvin Harris & Dua Lipa"]), true);
  assert.equal(m.artistsAgree(["The Beatles"], ["Beatles"]), true);
  assert.equal(m.artistsAgree(["TaylorSwift"], ["Taylor Swift"]), true);
  assert.equal(m.artistsAgree(["Queen"], ["Queen Latifah"]), false);
  assert.equal(m.artistsAgree([], ["Queen"]), false);
});

test("durations must agree within the tolerance for the pair", () => {
  assert.equal(m.toleranceFor("spotify", "apple_music"), 3000);
  assert.equal(m.toleranceFor("youtube", "spotify"), 5000);
  assert.equal(m.durationAgrees(200000, 202900, 3000), true);
  assert.equal(m.durationAgrees(200000, 203100, 3000), false);
  assert.equal(m.durationAgrees(0, 200000, 3000), false);
  assert.equal(m.parseIsoDuration("PT3M25S"), 205000);
  assert.equal(m.parseIsoDuration("PT1H2M"), 3720000);
});

test("youtube metadata: auto-generated description beats the title", () => {
  const desc = "Provided to YouTube by Universal Music Group\n\nBohemian Rhapsody · Queen\n\nA Night At The Opera\n\n℗ 1975";
  const a = m.parseYouTubeMeta("Bohemian Rhapsody (Remastered 2011)", "Queen - Topic", desc);
  assert.deepEqual(a, { title: "Bohemian Rhapsody", artists: ["Queen"], autoGenerated: true });
  const b = m.parseYouTubeMeta("Queen – Bohemian Rhapsody (Official Video Remastered)", "Queen Official", "");
  assert.equal(b.artists[0], "Queen");
  assert.equal(m.parseTitle(b.title).base, "bohemian rhapsody");
});

const SRC = { provider: "apple_music", title: "Bohemian Rhapsody", artists: ["Queen"], durationMs: 354947, isrc: "GBUM71029604" };

function sp(id, extra) {
  return Object.assign({ provider: "spotify", id: id, title: "Bohemian Rhapsody", artists: ["Queen"],
    durationMs: 354320, isrc: "GBUM71029604", albumType: "album", releaseDate: "1975-11-21" }, extra || {});
}

test("one ISRC on several releases is one recording; the album copy is chosen", () => {
  const r = m.decide(SRC, [sp("single00000000000000001", { albumType: "single", releaseDate: "1975-10-31" }), sp("album000000000000000001")],
    { target: "spotify", isrc: SRC.isrc });
  assert.equal(r.matched, true);
  assert.equal(r.candidate.id, "album000000000000000001");
});

test("different recordings that both agree are ambiguous, never guessed", () => {
  const r = m.decide(SRC, [sp("a0000000000000000000001"), sp("b0000000000000000000001", { isrc: "GBUM71111111" })], { target: "spotify" });
  assert.equal(r.matched, false);
  assert.equal(r.reason, "ambiguous");
});

test("a live or remastered candidate does not match a studio source", () => {
  const r = m.decide(SRC, [sp("a0000000000000000000001", { title: "Bohemian Rhapsody - Live Aid" }),
    sp("b0000000000000000000001", { title: "Bohemian Rhapsody - Remastered 2011" })], { target: "spotify" });
  assert.equal(r.matched, false);
  assert.equal(r.reason, "no_match");
  assert.deepEqual(r.evidence.rejected[0].reasons, ["version"]);
});

test("ISRC path refuses candidates lacking that ISRC and ones out of duration", () => {
  const r = m.decide(SRC, [sp("a0000000000000000000001", { isrc: "USXXX0000001" }), sp("b0000000000000000000001", { durationMs: 360000 })],
    { target: "spotify", isrc: SRC.isrc });
  assert.equal(r.matched, false);
  assert.deepEqual(r.evidence.rejected.map((x) => x.reasons.join()), ["isrc", "duration"]);
});

function yt(id, extra) {
  return Object.assign({ provider: "youtube", id: id, title: "Bohemian Rhapsody", artists: ["Queen"], durationMs: 355000,
    channel: "Queen - Topic", licensed: true, privacy: "public", uploadStatus: "processed", live: false, categoryId: "10" }, extra || {});
}

test("youtube: Topic upload preferred over the VEVO video", () => {
  const r = m.decide(SRC, [yt("vevo0000001", { channel: "QueenVEVO", durationMs: 359000 }), yt("topic000001")], { target: "youtube" });
  assert.equal(r.matched, true);
  assert.equal(r.candidate.id, "topic000001");
});

test("youtube: non-music, private, live or unrelated channels are not targets", () => {
  const r = m.decide(SRC, [
    yt("a0000000001", { categoryId: "22" }),
    yt("b0000000001", { privacy: "unlisted" }),
    yt("c0000000001", { live: true }),
    yt("d0000000001", { channel: "Random Uploads", licensed: false }),
  ], { target: "youtube" });
  assert.equal(r.matched, false);
  assert.ok(r.evidence.rejected.every((x) => x.reasons.indexOf("channel") !== -1));
});

test("youtube: two Topic uploads of the same song are ambiguous", () => {
  const r = m.decide(SRC, [yt("topic000001"), yt("topic000002")], { target: "youtube" });
  assert.equal(r.matched, false);
  assert.equal(r.reason, "ambiguous");
});

test("resource mappers read the provider shapes", () => {
  const s = m.fromSpotifyTrack({ id: "x", name: "N", artists: [{ name: "A" }], duration_ms: 1000,
    external_ids: { isrc: "gb-um7-10-29604" }, album: { album_type: "single", release_date: "2020" } });
  assert.equal(s.isrc, "GBUM71029604");
  assert.equal(m.fromSpotifyTrack({ id: "x", is_local: true }), null);
  const a = m.fromAppleSong({ id: "1", attributes: { name: "N", artistName: "A", durationInMillis: 5, isrc: "GBUM71029604", albumName: "N - Single" } });
  assert.equal(a.albumType, "single");
  const v = m.fromYouTubeVideo({ id: "dQw4w9WgXcQ", snippet: { title: "Rick Astley - Never Gonna Give You Up (Official Video)",
    channelTitle: "Rick Astley", categoryId: "10", liveBroadcastContent: "none" },
    contentDetails: { duration: "PT3M33S", licensedContent: true }, status: { privacyStatus: "public", uploadStatus: "processed" } });
  assert.equal(v.artists[0], "Rick Astley");
  assert.equal(v.durationMs, 213000);
  assert.equal(m.youtubeTier(v, ["Rick Astley"]), 2);
});

test("search terms carry qualifiers but no brackets or credits", () => {
  const t = m.searchTerms({ title: "Song (feat. X) - Live", artists: ["Band"] });
  assert.equal(t.title, "Song");
  assert.equal(t.artist, "Band");
  assert.deepEqual(t.qualifiers, ["live"]);
});

test("search terms offer the first name of a joint credit", () => {
  assert.equal(m.searchTerms({ title: "Song", artists: ["300SkullsAndCounting & Jenny Sparks"] }).firstArtist, "300SkullsAndCounting");
  assert.equal(m.searchTerms({ title: "Song", artists: ["A, B and C"] }).firstArtist, "A");
  assert.equal(m.searchTerms({ title: "Song", artists: ["Calvin Harris feat. Dua Lipa"] }).firstArtist, "Calvin Harris");
  assert.equal(m.searchTerms({ title: "Song", artists: ["Simon & Garfunkel"] }).artist, "Simon & Garfunkel");
  assert.equal(m.searchTerms({ title: "Song", artists: ["Jamie xx"] }).firstArtist, "");
});

test("rejected candidates keep what they were, for the owner panel", () => {
  const r = m.decide({ provider: "youtube", title: "Song", artists: ["A"], durationMs: 213000 },
    [{ provider: "spotify", id: "s1", title: "Song", artists: ["A"], durationMs: 190000, isrc: "" }], { target: "spotify" });
  assert.equal(r.matched, false);
  assert.deepEqual(r.evidence.rejected[0], { id: "s1", title: "Song", artists: ["A"], duration_ms: 190000, reasons: ["duration"] });
});

test("best guess: a joint credit a little off in length is still picked, album first", () => {
  const src = { provider: "youtube", title: "The Ballad of St Nick's Park", artists: ["300SkullsAndCounting & Jenny Sparks"], durationMs: 213000 };
  const c = (id, albumType) => ({ provider: "spotify", id: id, title: "The Ballad of St Nick's Park",
    artists: ["300SkullsAndCounting", "Jenny Sparks"], durationMs: 194000, isrc: "", albumType: albumType });
  const g = m.bestGuess(src, [c("single1", "single"), c("album1", "album")], { target: "spotify" });
  assert.equal(g.candidate.id, "album1");
  assert.equal(g.confidence, "likely");
  assert.deepEqual(g.notes, ["length (3:14 vs 3:33)"]);
});

test("best guess: a YouTube video with extra words in its title, or off the music channel", () => {
  const src = { provider: "spotify", title: "Idontknow", artists: ["Jamie xx"], durationMs: 322000 };
  const yt = (id, title, cat, ms) => ({ provider: "youtube", id: id, title: title, artists: ["Jamie xx"], durationMs: ms,
    channel: "Jamie xx", privacy: "public", uploadStatus: "processed", live: false, categoryId: cat, licensed: false });
  const g = m.bestGuess(src, [yt("v7", "Idontknow (7\" Version)", "10", 225000), yt("oona", "Idontknow (Oona Video)", "10", 322000)], { target: "youtube" });
  assert.equal(g.candidate.id, "oona");
  const h = m.bestGuess(src, [yt("plain", "Idontknow", "22", 322000)], { target: "youtube" });
  assert.equal(h.candidate.id, "plain");
  assert.ok(h.notes.some((n) => n.startsWith("channel")));
  assert.equal(m.bestGuess(src, [Object.assign(yt("priv", "Idontknow", "10", 322000), { privacy: "private" })], { target: "youtube" }), null);
});

test("best guess never crosses to another kind of recording or another artist", () => {
  const live = { provider: "spotify", title: "Song C - Live", artists: ["Band"], durationMs: 250000 };
  assert.equal(m.bestGuess(live, [{ provider: "apple_music", id: "1", title: "Song C", artists: ["Band"], durationMs: 250500 }], { target: "apple_music" }), null);
  const queen = { provider: "spotify", title: "Under Pressure", artists: ["Queen"], durationMs: 248000 };
  assert.equal(m.bestGuess(queen, [{ provider: "apple_music", id: "2", title: "Under Pressure", artists: ["Queen Latifah"], durationMs: 248000 }], { target: "apple_music" }), null);
  assert.equal(m.bestGuess(queen, [{ provider: "apple_music", id: "3", title: "Bohemian Rhapsody", artists: ["Queen"], durationMs: 248000 }], { target: "apple_music" }), null);
  const remaster = m.bestGuess(queen, [{ provider: "apple_music", id: "4", title: "Under Pressure (Remastered 2011)", artists: ["Queen"], durationMs: 248000 }], { target: "apple_music" });
  assert.equal(remaster.candidate.id, "4");
});

test("best guess between two equal recordings says so", () => {
  const src = { provider: "spotify", title: "Echo Chamber", artists: ["Echo"], durationMs: 200000 };
  const g = m.bestGuess(src, [
    { provider: "apple_music", id: "1", title: "Echo Chamber", artists: ["Echo"], durationMs: 200500, isrc: "USCCC2400001", albumType: "album" },
    { provider: "apple_music", id: "2", title: "Echo Chamber", artists: ["Echo"], durationMs: 199800, isrc: "USDDD2400001", albumType: "album" },
  ], { target: "apple_music" });
  assert.equal(g.candidate.id, "1");
  assert.equal(g.confidence, "unsure");
  assert.deepEqual(g.notes, ["1 other close candidate"]);
});

test("a Bandcamp track page: JSON-LD first, then the Open Graph title and page properties", () => {
  const ld = '<script type="application/ld+json">' + JSON.stringify({
    "@type": "MusicRecording", name: "Ash", byArtist: { "@type": "MusicGroup", name: "Body Void" },
    duration: "P00H07M05S", additionalProperty: [{ name: "track_id", value: 123456 }],
  }) + "</script>";
  const a = m.fromBandcampPage("<html><head>" + ld + "</head></html>", "bodyvoid/ash");
  assert.equal(a.title, "Ash");
  assert.deepEqual(a.artists, ["Body Void"]);
  assert.equal(a.durationMs, 425000);
  assert.equal(a.trackId, "123456");
  assert.equal(a.url, "https://bodyvoid.bandcamp.com/track/ash");

  const og = '<meta property="og:title" content="Rock &amp; Roll, by Tom, Dick &amp; Harry">' +
    '<meta name="bc-page-properties" content="{&quot;item_type&quot;:&quot;t&quot;,&quot;item_id&quot;:42}">';
  const b = m.fromBandcampPage(og, "tdh/rock-roll");
  assert.equal(b.title, "Rock & Roll");
  assert.deepEqual(b.artists, ["Tom, Dick & Harry"]);
  assert.equal(b.durationMs, 0);
  assert.equal(b.trackId, "42");

  assert.equal(m.fromBandcampPage("<html>nothing here</html>", "x/y"), null);
  assert.equal(m.toleranceFor("bandcamp", "spotify"), 5000);
});
